server:
  port: 8091


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.105.51:3306/${MYSQL_DATABASE:springboot_demo}
    username: app
    password: Aos.20250717
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
