server:
  port: 8091


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:10.14.111.234:3306}/${MYSQL_DATABASE:springboot_demo}
    username: root
    password: E7UCejVw
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
